# .readthedocs.yaml

version: 2

build:
    image: stable

sphinx:
    builder: html
    configuration: docs/source/conf.py
    fail_on_warning: true

python:
    # Install our Python packages before building the doc
    version: 3.8
    install:
        - requirements: requirements.txt
        - requirements: docs/requirements.txt

system_packages: true
