# .readthedocs.yaml

version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"

sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: true

formats:
    - pdf

python:
    # Install our Python packages before building the doc
    version: 3.11
    install:
        - requirements: requirements.txt
        - requirements: docs/requirements.txt

    system_packages: true
